name: Release

concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Default release branch
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/.ts/**'
      - '**/.nx/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    if: ${{ false }} # disable for now
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
      nexus-api-key: ${{ secrets.NEXUS_API_KEY }}
      nexus-cookie-nxid-header: ${{ secrets.NEXUS_COOKIE_HEADER_NEXUSID }}
      nexus-cookie-sid-header: ${{ secrets.NEXUS_COOKIE_HEADER_SID_DEVELOP }}
      nuget-org-key: ${{ secrets.NUGET_ORG_PAT }}
      ts-api-key: ${{ secrets.TS_SERVICEACCOUNT }}
      webhook_url: ${{ secrets.VALHEIM_DISCORD_TITANS_WEBHOOK_URL }}

    with:
      sln-file-name: Digitalroot.Valheim.EarlyWishbone
      proj-file-name: Digitalroot.Valheim.EarlyWishbone
      #src-path: src
      #unit-test-path: UnitTests
      #skip-unit-tests: true
      #force-assembly-version: true
      #create-github-release: false
      #aws-region: us-west-2
      #is-nuget-package: false
      #nuget-gh-upload: true
      #nuget-s3-upload: true
      #nuget-org-upload: true
      nexus-enable-upload: true
      nexus-mod-id: 2840
      ts-enable-upload: true
      ts-name: Early_Wishbone
      Ts-description: "Add the Wishbone to Eikthyr with a 25% chance to drop"
      ts-categories: "client-side" #https://thunderstore.io/api/experimental/community/valheim/category/
      ts-dependencies: ValheimModding-Jotunn-2.20.0
